name: Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Checkout Pygments
      uses: actions/checkout@v2
    - name: Install Sphinx & WCAG contrast ratio
      run: pip install Sphinx wcag-contrast-ratio
    - name: Pyodide build
      run: |
        cd doc
        make pyodide
    - name: Debug
      run: |
        ls -la ./doc/_build/dirhtml/pyodide/pyodide
    - name: Sphinx build
      run: |
        cd doc
        WEBSITE_BUILD=1 make dirhtml
        touch _build/dirhtml/.nojekyll
        echo -e 'pygments.org\nwww.pygments.org' > _build/dirhtml/CNAME
        echo 'Automated deployment of docs for GitHub pages.' > _build/dirhtml/README
    - name: Debug
      run: |
        ls -la ./doc/_build/dirhtml/_static
        ls -la ./doc/_build/dirhtml/_static/pyodide
    - name: Deploy to repo
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/_build/dirhtml
